// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmIpZUBS3oEcNsagHHhAcOMUsEfkACuJc',
    appId: '1:205883409914:web:df7a9005ea59f72ec89043',
    messagingSenderId: '205883409914',
    projectId: 'map-9f56b',
    authDomain: 'map-9f56b.firebaseapp.com',
    storageBucket: 'map-9f56b.firebasestorage.app',
    measurementId: 'G-R96NZR12XF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjUKrHtp7Q8enwNfTmbUTLMmNhBRVwOl8',
    appId: '1:205883409914:android:ce95bc5d4dfe89ebc89043',
    messagingSenderId: '205883409914',
    projectId: 'map-9f56b',
    storageBucket: 'map-9f56b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCpPdxF1YWTEowBZy0IqEUScLi7lbAez4',
    appId: '1:205883409914:ios:8ca7883dcfff9028c89043',
    messagingSenderId: '205883409914',
    projectId: 'map-9f56b',
    storageBucket: 'map-9f56b.firebasestorage.app',
    iosBundleId: 'com.example.gradProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCpPdxF1YWTEowBZy0IqEUScLi7lbAez4',
    appId: '1:205883409914:ios:8ca7883dcfff9028c89043',
    messagingSenderId: '205883409914',
    projectId: 'map-9f56b',
    storageBucket: 'map-9f56b.firebasestorage.app',
    iosBundleId: 'com.example.gradProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmIpZUBS3oEcNsagHHhAcOMUsEfkACuJc',
    appId: '1:205883409914:web:9b20c641c55c6cf7c89043',
    messagingSenderId: '205883409914',
    projectId: 'map-9f56b',
    authDomain: 'map-9f56b.firebaseapp.com',
    storageBucket: 'map-9f56b.firebasestorage.app',
    measurementId: 'G-KJ9GRN5RVC',
  );
}
